### ISSUE TITLE
Cloning static readonly fails in .Net Core 3.0

### ISSUE THREAD

**Issue by andyesys** [replaysMike/AnyClone#11]
I tried to clone a NodaTime.Period and it throws this exception: `System.FieldAccessException: Cannot set initonly static field '<Zero>k__BackingField' after type 'NodaTime.Period' is initialized.`

Related to https://github.com/dotnet/standard/issues/1598

**Comment by andyesys** [comment]
I can clone a NodaTime.Period by ignoring the Zero Property with `Periods.Clone("Zero")`.

But I think not cloning readonly statics should be the default behaviour.

**Comment by replaysMike** [comment]
I see this as well, and I’m pretty sure I know the cause as it’s affecting
multiple features. It’s due to a change in the .net core runtime support
for static read only fields.

I will work on a workaround for this right away.

**Comment by replaysMike** [comment]
This issue is now closed. I was able to get around this limitation (.net core 3+ reflection) by utilizing some IL to override accessibility of those values.
