### ISSUE TITLE
Change of license?

### ISSUE THREAD

**Issue by SmithPlatts** [replaysMike/AnyClone#15]
Howdy!

Would there be any chance of changing the license to MIT or some such? I'm in a situation where this library, so far, is the only one that seems to handle the deep cloning of a `Swashbuckle.Application.SwaggerDocsConfig` object.

Where I need to use it, however, is in a product that cannot be licensed under GPL, so the copyleft nature would in fact prevent me from using this.

I realise that this is likely too big a pain, but thought it worth asking.

Thanks!

**Comment by replaysMike** [comment]
Yes I’d be willing to change the license to MIT. The GPL was more of a
placeholder, as this repo can be used unrestricted in any project. I’ll
update it this afternoon

**Comment by SmithPlatts** [comment]
Thank you Mike!

**Comment by SmithPlatts** [comment]
Would you be willing to update the license on NuGet, too?

**Comment by replaysMike** [comment]
Done - the nuget package is updated to MIT as well, should be correct for v1.1.6

**Comment by SmithPlatts** [comment]
Confirmed

![image](https://user-images.githubusercontent.com/4887937/174529817-33636e58-2973-46d3-b3cf-7f79672388fc.png)

Thank you!!
