### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by andreaslennartz** [replaysMike/AnyClone#21]
Hi,
thanks for creating and sharing this great cloning library!

I was using DeepCloner in the past for cloning objects, but ran into some concurrency issues when using the library. After some investigation of the source code of DeepCloner, I came to the conclusion that DeepCloner seems not to be thread-safe, and even if I would be able to fix the issue, the code base would be hard to maintain. I am currently looking for a replacement, so I decided to have a deeper look at the other libraries. 

I checked out the "FastDeepCloner" library, which implementation looks solid. But the "FastDeepCloner" contains a lot of code blocks that are untested - though there is a test project, it only covers the very basics. 

So I am currently in Favor or this library - I think that this has the most potential. I really liked that there are already many tests in place. I already did some testing, and would like to continue to work with this library. 

Before I create an PR requests etc., just wanted to get in touch and see if this library is still actively maintained?

**Comment by Barshan-Mandal** [comment]
no

**Comment by StevenTCramer** [comment]
Are you having an issue with it?

**Comment by andreaslennartz** [comment]
I had, regarding the cloning of dyamic objects (which is a missing feature)
I had a look at the existing cloning libraries (DeepCloner, FastDeepCloner, this one), and I am currently creating a new implementation.
